
# Estagio 1 - Será responsavel em construir nossa aplicação
FROM node:latest
WORKDIR /app
COPY package.json /app/
RUN npm install
COPY . /app
ARG env=prod
RUN npm run build
EXPOSE 4200
ENTRYPOINT ["npm", "start"]