version: '3'

services:

    serverApi:
        image: eventos.api:prod
        build: 
            context: ./server
            dockerfile: Dockerfile.prod
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production

    nginx:
        image: eventos.client:prod
        build: 
            context: ./client
            dockerfile: Dockerfile.prod
        ports: 
            - "8080:8080"
            - "8287:8286"
        links:
            - serverApi