version: '3'

services:

    client:
        image: eventos.io.client:dev
        build: 
            context: ./client
            dockerfile: Dockerfile.dev
        volumes: 
            - ./client:/dev

    serverApi:
        image: eventos.api:prod
        build: 
            context: ./server/src/Eventos.IO.Services.Api
            dockerfile: Dockerfile.dev
        environment: 
            - ASPNETCORE_ENVIRONMENT=Development

    nginx:
        image: eventos.proxy:dev
        build: 
            context: ./nginx
            dockerfile: Dockerfile.dev
        ports: 
            - "8080:8080"
            - "8287:8286"
        links:
            - client
            - serverApi